apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-ellora
  labels:
    type: local
spec:
  storageClassName: database-ellora
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/var/lib/mysql/ellora"